### ISSUE TITLE
[SP9] ACPI error spam in dmesg after closing the type cover with the device plugged in

### ISSUE THREAD

**Issue by 3xfc** [linux-surface/linux-surface#1082]
If I close the type cover when my SP9 is plugged in, the dmesg log gets spammed with the following. The memory usage also goes up to around 7 GB with nothing open and the system slows down drastically. It also gets stuck when trying to reboot or shut down, so a hard shutdown is required.

### Environment

- Hardware model: Surface Pro 9 (Intel)
- Kernel version: 6.2 (Also occurs on the latest 6.1.13 Surface kernel)
- Distribution: Fedora Silverblue

<details><summary>`dmesg` output</summary>

```
[ 2694.375126] ACPI Error: No handler or method for GPE 51, disabling event (20221020/evgpe-839)
[ 2694.375133] ACPI Error: No handler or method for GPE 53, disabling event (20221020/evgpe-839)
[ 2694.375137] ACPI Error: No handler or method for GPE 54, disabling event (20221020/evgpe-839)
[ 2694.375141] ACPI Error: No handler or method for GPE 55, disabling event (20221020/evgpe-839)
[ 2694.375146] ACPI Error: No handler or method for GPE 56, disabling event (20221020/evgpe-839)
[ 2694.375150] ACPI Error: No handler or method for GPE 57, disabling event (20221020/evgpe-839)
[ 2694.375155] ACPI Error: No handler or method for GPE 60, disabling event (20221020/evgpe-839)
[ 2694.375164] ACPI Error: No handler or method for GPE 63, disabling event (20221020/evgpe-839)
[ 2694.375169] ACPI Error: No handler or method for GPE 64, disabling event (20221020/evgpe-839)
[ 2694.375173] ACPI Error: No handler or method for GPE 65, disabling event (20221020/evgpe-839)
[ 2694.375180] ACPI Error: No handler or method for GPE 67, disabling event (20221020/evgpe-839)
[ 2694.375184] ACPI Error: No handler or method for GPE 68, disabling event (20221020/evgpe-839)
[ 2694.375191] ACPI Error: No handler or method for GPE 6A, disabling event (20221020/evgpe-839)
[ 2694.375196] ACPI Error: No handler or method for GPE 6B, disabling event (20221020/evgpe-839)
[ 2694.375200] ACPI Error: No handler or method for GPE 6C, disabling event (20221020/evgpe-839)
[ 2694.375207] ACPI Error: No handler or method for GPE 6E, disabling event (20221020/evgpe-839)
[ 2694.375214] ACPI Error: No handler or method for GPE 70, disabling event (20221020/evgpe-839)
[ 2694.375218] ACPI Error: No handler or method for GPE 71, disabling event (20221020/evgpe-839)
[ 2694.375223] ACPI Error: No handler or method for GPE 72, disabling event (20221020/evgpe-839)
[ 2694.375230] ACPI Error: No handler or method for GPE 74, disabling event (20221020/evgpe-839)
[ 2694.375234] ACPI Error: No handler or method for GPE 75, disabling event (20221020/evgpe-839)
[ 2694.375239] ACPI Error: No handler or method for GPE 76, disabling event (20221020/evgpe-839)
[ 2694.375243] ACPI Error: No handler or method for GPE 77, disabling event (20221020/evgpe-839)
[ 2694.375290] ACPI Error: No installed handler for fixed event - PM_Timer (0), disabling (20221020/evevent-266)
[ 2694.375294] ACPI Error: No installed handler for fixed event - PowerButton (2), disabling (20221020/evevent-266)
[ 2694.375297] ACPI Error: No installed handler for fixed event - SleepButton (3), disabling (20221020/evevent-266)
[ 2694.375302] ACPI Error: Could not disable RealTimeClock events (20221020/evxfevnt-243)

```

</details>

**Comment by RalphBariz** [comment]
Can confirm issue, however I temporarily fixed it by adding "intel_idle.max_cstate=0" to GRUB_CMDLINE_KERNEL_DEFAULT
due to https://www.kernel.org/doc/html/latest/admin-guide/pm/cpuidle.html?highlight=max_cstate that means

> Adding intel_idle.max_cstate=0 to the kernel command line disables the intel_idle driver and allows acpi_idle to be used

I interpret that as using ACPI states rather than intel c-states. What is the impact on battery life I do not know yet.
However the spamming situation was bad. Spamming disk, spamming memory and spamming CPU.

**Comment by RalphBariz** [comment]
Switching to acpi_idle just lowered probability to get this symptom but it still occured. Another attempt worked out better.

To /etc/systemd/sleep.conf add:
```
[Sleep]
AllowSuspend=yes
AllowHibernation=no
AllowSuspendThenHibernate=no
AllowHybridSleep=no
```

Hibernate and HybridSleep seems to be the cause for both, spamming errors and device not coming up from sleep. Again, the effects on battery drain during sleep could be disturbing. For me, since it is mostly powered for the moment, is more important that it is reliably usable when waking it up.

**Comment by peter-marshall5** [comment]
That seems interesting. I'll try the workaround myself.

However, I also got this symptom to happen when the device was plugged in and set to ignore the lid switch. Maybe going into sleep takes the kernel / firmware out of a glitched state?

**Comment by RalphBariz** [comment]
While it reliably wakes up now, ACPI GPE storm seems not completely gone, still getting it but rarely now. However I see still chances to get rid of that.

First there is acpi_osi=! acpi_osi='Windows 2020' kernel parameter which shall tell firmware it is about Windows and it provides the Windows interfaces to Linux which shall be compatible with them. However this will be trying around with different windows versions. But since we are talking about M$ it's highly probable, that this is an intended bug to keep people at using windows on the surface.
https://discovery.endeavouros.com/acpi-kernel-parameters/acpi-kernel-parameters-and-how-to-choose-them/2021/03/

Second it is possible to prevent the ACPI GPE stom by masking the GPE events using acpi_mask_gpe=0x51.
However this might end up in a hack of a kernel commandline since there are multiple interrupts affected.

**Comment by RalphBariz** [comment]
Yeah, funny thing. While Windows 2015 is contained in DSDT table Windows 2020 isn't. However, Windows 2015 shows same symptoms while 2020 ran stable till now. Always waking up even from deep sleep. On power without GPE storm. Only acpi_osi=! also fails. So it's not like, Windows 2020 doing the same as nothing. 

Due to intentional bugs... well, I'm with Linux since earlier times, 90s.
And yes, it was always a fight. Still in Windows 7 era, updates regulary broke grub. That bug was also always a big complaining towards M$ and it never got better but even worse. That's only working out since M$ plays the Linux friend. But, strategies change... the typical character and interesst of manager not so much.

**Comment by peter-marshall5** [comment]
Interesting. For me, adding `acpi_osi="Windows 2020"` to the cmdline does not seem to have any effect, and `acpi_osi=! acpi_osi="Windows 2020"` does not seem to work either. Suspend seems to always work for me, and the bug is only triggered by closing the type cover while the device is powered on and plugged in. It also doesn't seem to happen after the first suspend. Maybe the OS is expected to set up GPE events manually, so this may be fixed when the `surface-gpe` module supports the SP9.

**Comment by qzed** [comment]
From my experience, MS doesn't do any OSI/OS matching shenanigans any more. So far, all ACPI related issues we've encountered were differences in how Windows and Linux treat things.

Regarding `surface-gpe` support: This module essentially configures the GPE associated with the lid/typecover to be wakeup capable. On the SP9, that is GPE 0x52. I'll add support for that, but I expect that this does not affect the issue.

The problem you're encountering seems to pretty much trigger every GPE around for some reason, however only some are handled. It complains about the ones without any associated handlers (notice how `52` is absent in the log above). So we need to figure out why pretty much every GPE is being triggered somehow.

**Comment by qzed** [comment]
> Regarding `surface-gpe` support: This module essentially configures the GPE associated with the lid/typecover to be wakeup capable. On the SP9, that is GPE 0x52. I'll add support for that, but I expect that this does not affect the issue. (The only effect it may have is that it will wake the device up if it gets triggered when suspended.)

Actually, can you provide the output of `sudo dmidecode -t system` for that (I don't need the serial number or UUID, just `Manufacturer`, `Product Name`, and `SKU`)?

**Comment by qzed** [comment]
The next releas should have wake-via-typecover support.

**Comment by vbauerster** [comment]
I suppose kernel >= 6.1 should solve this?

https://www.phoronix.com/news/Linux-6.1-MS-Surface-Pro-9

**Comment by qzed** [comment]
The ACPI error spam? Unfortunately not. The patches described in that article are the SAM/EC ones. So essentially typecover and battery support and have been in our kernels for a while. I am still unsure where the GPE spam comes from, but that's probably rather something ACPI, CPU, or chipset related.

**Comment by peter-marshall5** [comment]
Just saying that this is still not fixed as of kernel `6.4.4`. Booting with the option `acpi=noirq` stops this issue from happening but also breaks type cover support.

**Comment by RalphBariz** [comment]
Dind't have GPE storm for a while with deactivated deep sleep. However still having problems when shutting down and a slow wake up. I figured out, that battery saver BIOS setting might have a play with this. It obviously has a problem with the information of discharging during it is connected to AC.

**Comment by peter-marshall5** [comment]
I haven't had a GPE storm come up since applying these settings in my TLP config. Not sure exactly which option mitigates the issue yet. I am running Linux 6.7.1 in case that matters.

```
CPU_ENERGY_PERF_POLICY_ON_AC=balance_performance
CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power
PCIE_ASPM_ON_BAT=powersupersave
PLATFORM_PROFILE_ON_AC=balanced
PLATFORM_PROFILE_ON_BAT=low-power
RUNTIME_PM_ON_AC=auto
RUNTIME_PM_ON_BAT=auto
SOUND_POWER_SAVE_CONTROLLER=
```

**Comment by peter-marshall5** [comment]
I had to modify the GPE driver by adding a space at the beginning of the vendor string for it to load properly on my SP9. Suspend and resume using the lid switch works with it loaded, but it takes around 30 seconds to resume. I'm also getting a bit of GPE error spam in the dmesg logs right after resuming and the speakers start to make a periodic ticking noise. Maybe this is related to the root cause of the GPE spam issues above?

**Comment by cwittenberg** [comment]
Issue appears same as #1446 - I closed it to avoid redundancy but it may have relevant logs.

**Comment by peter-marshall5** [comment]
Could [this Linux commit](https://github.com/torvalds/linux/commit/b5539eb5ee70257520e40bb636a295217c329a50) be relevant?

**Comment by peter-marshall5** [comment]
I found that the speaker clicking noise after suspending via the lid stops after a minute or so, and suspending via the lid works properly again afterward. (Suspending otherwise would cause the device to get stuck.)

**Comment by peter-marshall5** [comment]
Just managed to get suspend via lid working while I was playing around with disabling GPE interrpts via `/sys/firmware/acpi/interrupts/gpeXX`. I'll try to narrow down the affected interrupt.

**Comment by peter-marshall5** [comment]
It seems like specifying `acpi_sci=edge` prevents the logs from being flooded with repeating ACPI errors, although the errors still appear once. It also seemingly prevents the lid switch from working more than once, though.

**Comment by 3xfc** [comment]
Just got waking up via the lid working without triggering the GPE spam bug. I added the required _PRW fields under the lid switch device in my DSDT and blacklisted `surface_gpe`. Here is a copy and paste of what I added inside `Device (LID0)`:

```
            Method (_PRW, 0, NotSerialized)  // _PRW: Power Resources for Wake
            {
                Return (GPRW (0x52, 0x04))
            }
```

Here is my entire modified DSDT: [dtdt.dsl.txt](https://github.com/user-attachments/files/16241307/dtdt.dsl.txt)

`GPRW` seems to generate packages for `_PRW` to return given a specified GPE and maximum power state that can be woken from.

The affected GPEs when the flooding bug is triggered include 0x50-0x57 and 0x60-0x77 IIRC (Related to PCI bus wakeups?) as well as some errors mentioning fixed interrupt events. The kernel is probably handling `_PRW` fields in a different way from `surface_gpe` to prevent the GPE spam bug from occurring.

Maybe `surface_gpe` could be updated to avoid the need for a patched DSDT?

**Comment by qzed** [comment]
IIRC I tried looking into adding the `_PRW` field from the kernel way back when I wrote the module, but I didn't find a clean way to do so. If you have any suggestions/pointers on how to improve the module, please let me know and I'll try to look into it.

**Comment by 3xfc** [comment]
Upon further testing it turns out that my DSDT edit causes issues with suspend via the power button - The device instantly wakes back up for some reason.

I just got the latest firmware update from Windows, and now GPE 52 gets enabled under Linux even without a PRW field (at least inside the DSDT). Suspend via the lid is working as if `surface_gpe` was loaded - resuming when the lid is opened works but the GPE spam bug is still triggered.

It seems like maybe something is generating ACPI interrupts and setting bogus GPE / fixed event flags before Linux is awake to service them? The interrupts run thousands of times on resume via the lid but seem to stop instead of continuing indefinitely as observed previously.

Maybe we could get Linux to read the lid switch GPIO directly, as that seems to be what the DSDT is doing anyways.

**Comment by 3xfc** [comment]
The GPE spam bug seems to be completely gone when booting with the option `pci=hpiosize=0`, suggested in [this bugzilla thread about a similar issue.](https://bugzilla.kernel.org/show_bug.cgi?id=203617) The root cause of the issue seems to be some PCI memory corruption bug.

Suspend / resume via the lid switch seems to be fully working with this parameter and `surface_gpe` loaded, although the device wakes up when closing the lid if it was already in standby.

Closing for now as this seems like a decent workaround.

**Comment by qzed** [comment]
@3xfc Thanks for figuring out that workaround! Could you add this to the wiki as well?

**Comment by gtxg16** [comment]
on the sp9 this fix works however opening the type cover from closed will no longer automatically wake it. is there a fix for that or do i have to choose between dmesg spam or wake on type cover opening

**Comment by petm5** [comment]
@gtxg16 do you have `surface_gpe` loaded?

**Comment by kwai-chang** [comment]
newly installed MX-Linux 25 /debian 13, surface Kernel 6.17.2
issue within minutes logs are written up to system limitation 50GB

how to load surface-gpe


[kern-log.txt](https://github.com/user-attachments/files/24379439/kern-log.txt)
[sys-log.txt](https://github.com/user-attachments/files/24379440/sys-log.txt)

**Comment by petm5** [comment]
@kwai-chang To fix the dmesg spam:

```bash
sudo nano /etc/default/grub
```

Go to the line starting with `GRUB_CMDLINE_LINUX=` and add this at the end but before the final quote:

```
pci=hpiosize=0
```

Press ctrl+x, y, enter to save, then run `sudo update-grub` and reboot

You can clear the logs with `sudo journalctl --vacuum-size=500M`

`surface-gpe` should load automatically, but you can make sure by running `sudo modprobe surface-gpe`

**Comment by kwai-chang** [comment]
> [@kwai-chang](https://github.com/kwai-chang) To fix the dmesg spam:
> 
> sudo nano /etc/default/grub
> Go to the line starting with `GRUB_CMDLINE_LINUX=` and add this at the end but before the final quote:
> 
> ```
> pci=hpiosize=0
> ```
> 
> Press ctrl+x, y, enter to save, then run `sudo update-grub` and reboot
> 
> You can clear the logs with `sudo journalctl --vacuum-size=500M`
> 
> `surface-gpe` should load automatically, but you can make sure by running `sudo modprobe surface-gpe`

edited grub, it works 

thx a lot
