### ISSUE TITLE
Touch input stopped working on SP8 with Arch Kernel 6.2.12-arch1-1-surface kernel

### ISSUE THREAD

**Issue by k4ever** [linux-surface/linux-surface#1123]
Touch input has stop working on Surface Pro 8 after updating Arch to kernel 6.2.12

### Environment

- Hardware model: Surface Pro 8
- Kernel version: 6.2.12-arch1-1-surface
- Distribution: EndeavourOS

```
please provide a copy of `dmesg` here if possible

https://pastebin.com/yJqzJs89

**Comment by StollD** [comment]
Does it work if you stop iptsd?

```bash
$ sudo systemctl stop $(iptsd-find-service)
```

Did you change anything in the iptsd config? Did you calibrate iptsd?

**Comment by k4ever** [comment]
No that doesn't work. Also, I haven't touched iptsd or calibrate anything. I just did the kernel upgrade. 

After the kernel update, I did a reboot and touch was actually working. However, when I put the device to sleep, touch stopped working. I had to open and close the keyboard cover a few times for it to start working again. This morning, when I took the SP8 off the charger, touch wasn't working again. 

I tried opening and closing the cover several times and rebooting several times. It just flat out stopped working.

**Comment by k4ever** [comment]
Update: It seems that iptsd is not loading:

systemctl start iptsd
Failed to start iptsd.service: Unit iptsd.service not found.

However, this command works from an older issue:
sudo /usr/bin/iptsd /dev/hidraw0

**Comment by k4ever** [comment]
sudo systemctl stop $(iptsd-find-service)

Returns nothing...

sudo systemctl status $(iptsd-find-service)
× iptsd@dev-hidraw0.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/usr/lib/systemd/system/iptsd@.service; static)
     Active: failed (Result: core-dump) since Sun 2023-04-23 11:23:43 EDT; >
   Duration: 5.236s
       Docs: https://github.com/linux-surface/iptsd
    Process: 399 ExecStart=/usr/bin/iptsd /dev/hidraw0 (code=dumped, signal>
   Main PID: 399 (code=dumped, signal=ABRT)
        CPU: 3ms

Apr 23 11:23:37 kelvin-surfacepro8 systemd[1]: Started Intel Precise Touch >
Apr 23 11:23:37 kelvin-surfacepro8 iptsd[399]: [11:23:37.983] [info] Metada>
Apr 23 11:23:37 kelvin-surfacepro8 iptsd[399]: [11:23:37.983] [info] rows=4>
Apr 23 11:23:37 kelvin-surfacepro8 iptsd[399]: [11:23:37.983] [info] width=>
Apr 23 11:23:37 kelvin-surfacepro8 iptsd[399]: [11:23:37.983] [info] transf>
Apr 23 11:23:37 kelvin-surfacepro8 iptsd[399]: [11:23:37.983] [info] unknow>
Apr 23 11:23:38 kelvin-surfacepro8 iptsd[399]: [11:23:38.042] [info] Connec>
Apr 23 11:23:43 kelvin-surfacepro8 iptsd[399]: iptsd: /usr/include/eigen3/E>
Apr 23 11:23:43 kelvin-surfacepro8 systemd[1]: iptsd@dev-hidraw0.service: M>
Apr 23 11:23:43 kelvin-surfacepro8 systemd[1]: iptsd@dev-hidraw0.service: F>
lines 1-19/19 (END)

**Comment by k4ever** [comment]
I got it to work! I think there was a typo in /usr/lib/systemd/system/iptsd@.service file:

[Unit]
Description=Intel Precise Touch & Stylus Daemon
Documentation=https://github.com/linux-surface/iptsd
StopWhenUnneeded=yes
BindsTo=%i.device

[Service]
Type=simple
#ExecStart=/usr/bin/iptsd /%I
ExecStart=/usr/bin/iptsd /%i


There was a capital "I" instead of a small "i". After changing this everything works fine.

**Comment by k4ever** [comment]
I spoke too soon. Multi-touch is not working!!

**Comment by k4ever** [comment]
Is this just a regression to this: https://github.com/linux-surface/linux-surface/issues/1048 ??

**Comment by StollD** [comment]
> There was a capital "I" instead of a small "i". After changing this everything works fine.

`%i` is the escaped instance name (dev-hidraw0), `%I` is the unescaped instance name (dev/hidraw0). You want `%I`.

 This is the same issue as https://github.com/linux-surface/iptsd/issues/124

**Comment by k4ever** [comment]
This regression is ridiculous! The only way to get multitouch to work on an SP8 is to run sudo /usr/bin/iptsd /dev/hidraw !!

I tried replacing ExecStart=/usr/bin/iptsd /%i with ExecStart=/usr/bin/iptsd /dev/hidraw and I get multitouch after boot, but as soon as a put the SP8 to sleep, it returns to single touch on wake. Why was iptsd changed again?

**Comment by StollD** [comment]
> The only way to get multitouch to work on an SP8 is to run sudo /usr/bin/iptsd /dev/hidraw !!

Then why edit around in a service file that does exactly that.

Its a bug in the daemon that makes it crash when it receives data from the hardware that it doesn't expect. When that data is sent is a question you need to as a Microsoft / Intel touchscreen engineer.

```
Apr 23 11:23:43 kelvin-surfacepro8 iptsd[399]: iptsd: /usr/include/eigen3/E>
```

Thats the important line. If you read the full line in the terminal, you will probably see its an assertion about an out of bound array access.

> Why was iptsd changed again?

The large changes in the latest iptsd release fix the Surface Pro 4 (and any other noisy device), which was basically unusuable before, and make maintaining iptsd much easier for me.

> This regression is ridiculous!

I agree that a regression that literally refuses to manifest in data captures and only occurs in real time usage on a specific device is ridiculous!

What do you think I am doing? Breaking things for fun?

My sample size when I work on iptsd is one. If my device doesn't show a certain bug, I cannot catch it during development. Thats why I let GitHub build every commit I push into packages that people can test on their devices. Nobody does.

So when there is a bug like this one, which only happens on a device I do not own, and which refuses to appear in a data capture that would allow me to debug it myself, all I can do is rely on someone else to find a way to reproduce it and then give me enough hints to fix it. Which happened in the issue I linked, I have a pretty good idea what could fix the issue. I just need someone to test the fix for me, because as I explained, I cannot do that myself.

**Comment by k4ever** [comment]
I didn't mean for my frustration to upset you. My Surface Pro 8 is my primary machine, so when something stops working on it, it causes a lot of anxiety on my part. Especially when I have to boot back into Windows.

 You are not alone. I may not be a programmer (I'm an engineer), but I am willing to help you out as much as I can. If you would like, you can send me an email with any new changes and I can test them out on my SP8 to ensure that they still work. 

I sincerely apologize for making you feel that your work was not appreciated.

**Comment by StollD** [comment]
On the other issue someone reported that my proposed fix does indeed solve the problem, so I pushed it. If you want, you can download a build from here: https://github.com/linux-surface/iptsd/actions/runs/4787961753

Scroll down and download the artifact <your distro>-latest. You will get a zip file with a package for your distribution inside. I would appreciate if you could try it out and report if the fix works for you too!

**Comment by k4ever** [comment]
I installed the Arch package and yes it works fine! I rebooted my SP8, then put it to sleep several times and touch/multitouch continue to work. Thank you!

I apologize again for letting my frustrations get the best of me.

**Comment by clabbin** [comment]
I've been having the same issue on my SP8 but in Fedora 38. Touch works upon boot but as soon as I put my device to sleep, touch stops working and doesn't work without a restart. I tried the Fedora 38 artifact posted by StollD and still having the same problem =/

**Comment by clabbin** [comment]
Now what is interesting is that I just installed manjaro 22.1 alongside my fedora 38 install and installed all the surface linux parts, as well as the arch artifact from StollD and it's working just fine waking from sleep. Seems to be a bigger issue going on in Fedora. I'll probably nuke my fedora install if manjaro keeps working properly.

**Comment by StollD** [comment]
How did you install the Fedora package? Can you get me a log from Fedora when it fails? (`dmesg` and `journalctl -b`)

**Comment by clabbin** [comment]
I initially installed it using the install rpm command in terminal, which didn't fix it. I then this morning I tried to install it using the yum command and for some reason, it's working after doing that.... not sure what else I may or may not have inadvertently done but I'm pretty positive that's all I did... I'll keep messing with it to see if it stops working and then I'll get you logs if it happens.

**Comment by clabbin** [comment]
So I have had it intermittently go out on both my Fedora install and Manjaro install but not as frequently as it was happening before. Next time it happens, I'll grab some logs for you.

**Comment by bastianandre** [comment]
I experienced a similar Problem on Surface Pro 9 with the 6.2.12 kernel on debian and the updated iptsd seems to have fixed the issue. 
Thanks @StollD :)

**Comment by m1nicrusher** [comment]
Same thing is happening to me on my Surface Laptop Studio, Fedora 38, kernel 6.2.13.
Service status shows something like core dumped. Restarting service doesn't seem to fix, but sometimes a fresh reboot of the laptop seems to temporarily resolve the issue. And then after a few sleep/wake, it stops working again.

I'm now using this solution, so far it works good for me (I'll keep it updated if I encounter any issue with this fix):

> On the other issue someone reported that my proposed fix does indeed solve the problem, so I pushed it. If you want, you can download a build from here: https://github.com/linux-surface/iptsd/actions/runs/4787961753
> 
> Scroll down and download the artifact -latest. You will get a zip file with a package for your distribution inside. I would appreciate if you could try it out and report if the fix works for you too!

**Comment by eduardhojbota** [comment]
> On the other issue someone reported that my proposed fix does indeed solve the problem, so I pushed it. If you want, you can download a build from here: https://github.com/linux-surface/iptsd/actions/runs/4787961753
> 
> Scroll down and download the artifact -latest. You will get a zip file with a package for your distribution inside. I would appreciate if you could try it out and report if the fix works for you too!

I had the same issue reported by @k4ever on SP8, Arch. I manually installed the package and currently it works. I will report if it stops working. Thank you.

**Comment by k4ever** [comment]
It's back with the latest kernel update...

**Comment by StollD** [comment]
Could you please post the log?

```bash
$ sudo systemctl status $(iptsd-find-service)
```

Ideally after a fresh boot, or right after it stops working.

**Comment by k4ever** [comment]
I apologize for taking so long. I had to run some errands this morning. Here is the output:

○ iptsd@-.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/usr/lib/systemd/system/iptsd@.service; static)
     Active: inactive (dead)
       Docs: https://github.com/linux-surface/iptsd

**Comment by StollD** [comment]
This indicates that the kernel driver didn't load. Could you post your dmesg?

**Comment by k4ever** [comment]
Sure thing:
[dmesg.txt](https://github.com/linux-surface/linux-surface/files/11465704/dmesg.txt)

**Comment by StollD** [comment]
It seems you have installed a different version of the ITHC driver with DKMS. Please don't do that.

The driver you have installed seems to be so old, it doesn't default to HID mode and instead uses its own userspace API (you can check if `/dev/ithc` exists to confirm this).

ITHC has been included in the surface kernel for quite a while and the code we are using is the most recent one, so please remove any DKMS installations of the module.

**Comment by k4ever** [comment]
I didn't do that. I just updated the Surface kernel and packages from the official Arch Surface repository, along with other packages, using EndeavourOS' "Update in Terminal" application.  I don't install drivers manually myself anymore. I've been using Linux for over 25 years and have done it in the past out of necessity. However, that hasn't been necessary for well over a decade. 

If there is an old errant ITHC driver installed, I did it because one of you folks (the excellent Surface Linux Development Team) told me to do it to fix an issue in the past. If so, I would greatly appreciate it if you can please tell me how to properly get rid of it.

BTW, I didn't mean to write the statement "the excellent Surface Linux Development Team" facetiously. I really appreciate what you folks do. It's just that the only time I stray from running packages on my system from the official Surface Linux repo is when one of you folks tell me to do it. If that's going to cause problems in the future, please let me know what I need to do to return my system to "normal" after the fact.

**Comment by StollD** [comment]
You need to clone the ITHC repository and then run `sudo make dkms-uninstall` in it: https://github.com/quo/ithc-linux

After that reinstall the surface kernel to be sure that you are using the builtin driver.

**Comment by k4ever** [comment]
Ouch! Just saw your comment afterwards. I was following these instructions:

https://stackoverflow.com/questions/63071339/how-can-i-delete-a-dkms-module-in-arch-linux

Hopefully, I didn't screw up anything..

**Comment by k4ever** [comment]
Ok, cloned the repository, then did:

[kelvin@kelvin-surfacepro8 ithc-linux]$ sudo make dkms-uninstall
[sudo] password for kelvin: 
modprobe -r ithc
dkms uninstall `sed -n '/^PACKAGE_NAME="\(.*\)"$/s//\1/p' dkms.conf`/`sed -n '/^PACKAGE_VERSION="\(.*\)"$/s//\1/p' dkms.conf` --all
Module ithc-0.1 for kernel 6.3.1-arch2-1-surface (x86_64).
Before uninstall, this module version was ACTIVE on this kernel.

ithc.ko.zst:
 - Uninstallation
   - Deleting from: /usr/lib/modules/6.3.1-arch2-1-surface/updates/dkms/
 - Original module
   - Archived original module found in the DKMS tree
   - Moving it to: /usr/lib/modules/6.3.1-arch2-1-surface/kernel/drivers/misc//
depmod...

Removing original_module from DKMS tree for kernel 6.3.1-arch2-1-surface (x86_64)
dkms remove `sed -n '/^PACKAGE_NAME="\(.*\)"$/s//\1/p' dkms.conf`/`sed -n '/^PACKAGE_VERSION="\(.*\)"$/s//\1/p' dkms.conf` --all
Module ithc 0.1 is not installed for kernel 6.3.1-arch2-1-surface (x86_64). Skipping...
Deleting module ithc-0.1 completely from the DKMS tree.
rm -rf /usr/src/`sed -n '/^PACKAGE_NAME="\(.*\)"$/s//\1/p' dkms.conf`-`sed -n '/^PACKAGE_VERSION="\(.*\)"$/s//\1/p' dkms.conf`
sync

[kelvin@kelvin-surfacepro8 ithc-linux]$ sudo pacman -S linux-surface linux-surface-headers
warning: linux-surface-6.3.1.arch2-1 is up to date -- reinstalling
warning: linux-surface-headers-6.3.1.arch2-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (2)                          Old Version    New Version    Net Change

linux-surface/linux-surface          6.3.1.arch2-1  6.3.1.arch2-1    0.00 MiB
linux-surface/linux-surface-headers  6.3.1.arch2-1  6.3.1.arch2-1    0.00 MiB

Total Installed Size:  271.00 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                     [--------------------] 100%
(2/2) checking package integrity                   [--------------------] 100%
(2/2) loading package files                        [--------------------] 100%
(2/2) checking for file conflicts                  [--------------------] 100%
:: Running pre-transaction hooks...
(1/1) Remove upgraded DKMS modules
==> dkms remove --no-depmod evdi/1.13.1 -k 6.3.1-arch2-1-surface
:: Processing package changes...
(1/2) reinstalling linux-surface                   [--------------------] 100%
(2/2) reinstalling linux-surface-headers           [--------------------] 100%
:: Running post-transaction hooks...
(1/6) Arming ConditionNeedsUpdate...
(2/6) Updating module dependencies...
(3/6) Install DKMS modules
==> dkms install --no-depmod evdi/1.13.1 -k 6.3.1-arch2-1-surface
==> depmod 6.3.1-arch2-1-surface
(4/6) Updating linux initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux-surface.preset: 'default'
  -> -k /boot/vmlinuz-linux-surface -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-surface.img
==> Starting build: '6.3.1-arch2-1-surface'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: 'xhci_pci'
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [consolefont]
==> WARNING: consolefont: no font found in configuration
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux-surface.img'
==> Image generation successful
==> Building image from preset: /etc/mkinitcpio.d/linux-surface.preset: 'fallback'
  -> -k /boot/vmlinuz-linux-surface -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-surface-fallback.img -S autodetect
==> Starting build: '6.3.1-arch2-1-surface'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: 'qla1280'
==> WARNING: Possibly missing firmware for module: 'aic94xx'
==> WARNING: Possibly missing firmware for module: 'bfa'
==> WARNING: Possibly missing firmware for module: 'qed'
==> WARNING: Possibly missing firmware for module: 'wd719x'
==> WARNING: Possibly missing firmware for module: 'qla2xxx'
==> WARNING: Possibly missing firmware for module: 'xhci_pci'
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [consolefont]
==> WARNING: consolefont: no font found in configuration
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux-surface-fallback.img'
==> Image generation successful
(5/6) Refreshing PackageKit...
(6/6) Checking which packages need to be rebuilt
foreign auto-cpufreq
foreign gnome-browser-connector

Will reboot now. Fingers crossed!

**Comment by k4ever** [comment]
I know there were others who had similar issues to my original post. However, my original issue has been solved for some time, so I'm closing this. Thanks for all your help. If there is an issue in the future, I will open a new ticket.

**Comment by StollD** [comment]
The iptsd fix is now released as iptsd 1.2.1
