### ISSUE TITLE
linux-headers-surface unmet dependecies

### ISSUE THREAD

**Issue by merhmerh** [linux-surface/linux-surface#1283]
I was following the guide until i met this error when executing this command:

`sudo apt install linux-image-surface linux-headers-surface libwacom-surface iptsd`

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 linux-headers-surface : Depends: linux-headers-6.5.7-surface-1 (= 6.5.7-surface-1-1) but it is not going to be installed
 linux-image-surface : Depends: linux-image-6.5.7-surface-1 (= 6.5.7-surface-1-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I have search the issues tab, and found similar problem but it was for different version.

### Environment
```
- Hardware model: Surface Pro 6
- Kernel version: Linux version 6.5.7-surface-1 (root@92a4db9508c6) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1 SMP PREEMPT_DYNAMIC Sun Oct 29 02:58:26 UTC 2023
- Distribution: Debian 12
```

**Comment by danthedev123** [comment]
Also currently experiencing this error when attempting to upgrade from a previous kernel (6.5.6 --> 6.5.7)

**Comment by Michael1260** [comment]
Yes,I also confirm the bug

**Comment by StollD** [comment]
I made a seemingly simply change but because of how our package scripts work this caused the meta packages to require a wrong version of the kernel package. `6.5.7-surface-1-1` instead of `6.5.7-surface-1`.

I think I fixed it and tagged a new build that should arrive in the repo in a few hours.

**Comment by Michael1260** [comment]
Thank you :-)

**Comment by Michael1260** [comment]
Still something wrong I believe 

root@SurfacePro4:/home/michael# sudo dpkg --list | egrep 'linux-image|linux-headers'
ii  linux-headers-6.5.0-10                           6.5.0-10.10                               all          Header files related to Linux kernel version 6.5.0
ii  linux-headers-6.5.0-10-generic                   6.5.0-10.10                               amd64        Linux kernel headers for version 6.5.0 on 64 bit x86 SMP
ii  linux-headers-6.5.7-surface-2                    6.5.7-surface-2                           amd64        Linux kernel headers for 6.5.7-surface-2 on amd64
ii  linux-headers-generic                            6.5.0.10.12                               amd64        Generic Linux kernel headers
ii  linux-headers-surface                            6.5.7-surface-2                           amd64        
ii  linux-image-6.5.0-10-generic                     6.5.0-10.10                               amd64        Signed kernel image generic
ii  linux-image-6.5.7-surface-2                      6.5.7-surface-2                           amd64        Linux kernel, version 6.5.7-surface-2
ii  linux-image-generic                              6.5.0.10.12                               amd64        Generic Linux kernel image
ii  linux-image-surface                              6.5.7-surface-2                           amd64        

So -2 is install and ok :
root@SurfacePro4:/home/michael# uname -a
Linux SurfacePro4 6.5.7-surface-2 #2 SMP PREEMPT_DYNAMIC Sun Oct 29 12:36:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

BUT :
apt update
....

root@SurfacePro4:/home/michael# apt install linux-image-surface linux-headers-surface
..cut..

Les paquets suivants contiennent des dépendances non satisfaites :
 linux-headers-surface : Dépend: linux-headers-6.5.7-surface-1 (= 6.5.7-surface-1-1) mais ne sera pas installé
 linux-image-surface : Dépend: linux-image-6.5.7-surface-1 (= 6.5.7-surface-1-1) mais ne sera pas installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
root@SurfacePro4:/home/michael# 

still surface-1

**Comment by danthedev123** [comment]
Looks like it, I am still unable to upgrade the kernel to the latest version.

**Comment by qzed** [comment]
Should be fixed now. The name change broke something in our repo automation (`reprepo` was detection the newer packages as being older). Please make sure to update the repo info (i.e., run `sudo apt update`) before attempting to install the packages.

**Comment by Michael1260** [comment]
Can confirm, it's fixed .. Thank you :-)

**Comment by danthedev123** [comment]
It's working, thanks a lot @qzed!

**Comment by merhmerh** [comment]
Can confirm too! Fixed for me, Thanks a lot!!

**Comment by phendrome** [comment]
I'm having issues installing this today on my Surface Pro 3.

```
sudo apt install linux-image-surface linux-headers-surface libwacom-surface iptsd
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-image-surface
E: Unable to locate package linux-headers-surface
E: Unable to locate package libwacom-surface
E: Unable to locate package iptsd

```
What should I do to fix the issue? I've tried following the official guide to install, until I encountered this issue. I also added `sudo add-apt-repository ppa:gpxbv/apt-urlfix` without success.
