### ISSUE TITLE
SL1 suspend-then-hibernate wakes up unexpectedly and gets very hot

### ISSUE THREAD

**Issue by CRBl69** [linux-surface/linux-surface#603]
While using `suspend-then-hibernate` with LUKS encryption, the laptop wakes up unexpectedly.

What usually happens is that i just close the lid (which is configured to do `suspend-then-hibernate` in my systemd logind.conf), put it in my backpack, and after some time (I would say about 10 minutes) it gets SUPER hot, it never gets this hot not even under heavy load. When i open up the lid, the screen is black but on, and i have to press the power button for a long time to shut it down.

I can not reproduce this consistently, as it only happens about 1 in 10 times or so, and I couldn't yet figure out a pattern or something that could trigger this.

Is this a common issue ? Could this be due to a missconfiguration from me or is this an actual software issue ?

### Environment

- Hardware model: Surface Laptop 1
- Kernel version: Linux furcase 5.14.11-arch1-2-surface #1 SMP PREEMPT Sun, 10 Oct 2021 17:58:33 +0000 x86_64 GNU/Linux
- Distribution: Arch Linux
- mkinitcpio hooks: `HOOKS=(base systemd autodetect keyboard sd-vconsole modconf block sd-encrypt filesystems fsck)`
- mkinitcpio modules: `MODULES=(surface_aggregator surface_aggregator_registry surface_hid_core surface_hid intel_lpss intel_lpss_pci 8250_dw surface_kbd)`
- I have this in my `/etc/systemd/logind.conf`: `HandleLidSwitch=suspend-then-hibernate`
- And this in my `/etc/systemd/sleep.conf`: `AllowSuspendThenHibernate=yes`

**Comment by qzed** [comment]
Can you try turning off bluetooth before suspending? AFAIK that has a tendency to wake the device.

Also can you try to figure out if the device gets hot when suspending or when resuming? Or does this happen when the device is fully resumed but closed due to some other crash?

You could try getting a log with `journalctl -b -<n>` where `<n>` is the number of boots since the issue happened. I.e. if the issue happens and you have to force shutdown the device, use `journalctl -b -1` on the next boot. This might not show much though if the system crashes during suspend, but it will show if something happens before or (if it even comes that far) after.

**Comment by qzed** [comment]
It looks like you're entering and leaving suspend quite often before. I assume that's you trying to trigger the issue? Another thing is that it resumes and switches into hibernation quite quickly, that is intended?

For the last suspend/resume cycle: It looks like the system enters and exits hibernation properly. There are some errors related to WiFi but nothing that we haven't seen before. Essentially, the card detects an error when resuming from suspend and resets itself, after which it looks like it should be working, I think. In any case can you try blacklisting `mwifiex` and `mwifiex_pci` temporarily and test if that changes anything?

Also, can you try to reproduce this issue with hibernation only?

**Comment by CRBl69** [comment]
Hi, sorry for my long silence.

Yes, I was trying to trigger the issue. And yes, the suspend to hibernate delay was very short so I didn't have to wait so long when I was trying to trigger it.

I disabled `mwifiex` and `mwifiex_pci` using kernel parameters (`module_blacklist=mwifiex,mwifiex_pci`) and used normal hibernation (no `suspend-then-hibernate`). Problem still occured.

[journalctl_dump.txt](https://github.com/linux-surface/linux-surface/files/8112362/journalctl_dump.txt)

Here is another dump of what happened.

Again, tried it multiple times before it triggered, and it triggered at my last attempt (23:03 to 23:18).

When I opened the lid, the screen was turned on and displaying the last thing that was on my screen (firefox in this case). I had to hold press on the power button for it to shut down. When I started the machine, the browser was still open, so that means it actually resumed.

I triggered the issue by closing the lid (I set the lid closing action to hibernate).

Should I try to trigger the issue by running `systemctl hibernate` instead ? Without closing the lid ?
