### ISSUE TITLE
Laptop 4 AMD suspend / hibernate wont wake up nomodset is only workaround...

### ISSUE THREAD

**Issue by DrBrad** [linux-surface/linux-surface#624]
Suspend / Hibernation
When my laptop goes into suspend from closing the lid, over time, or forceful suspend the laptop suspends. However I'm unable to wake the computer back up after the suspend. Heres what I have tried and noticed

The FN key light toggles fine under suspend however CAPS does not
The screen never turns on however keyboard backlight does
Pressing any key does not wake it even on external keyboard or mouse
It doesn't matter if the laptop is plugged in or not
I have tried changing the swapspace to 9GB, I have 8GB of ram, with no changes
I have tried changing grub with `nouveau.modeset=0` with no changes, however that seems like an NVidia solve anyways.

Currently the only way to fix this is by turning off the computer then turning it back on.
I have just disabled suspend in every way until its fixed, because every time it goes into suspend it will force me to shutdown now.

### Environment

- Hardware model: Surface Laptop 4 (AMD)
- Kernel version: 5.14.13 - 5.14.15 (It happens allot less in previous versions)
- Distribution: Ubuntu 20.04

**Comment by PiecePaperCode** [comment]
I fixed my problem with hibernation by first installing the newest firmware from microsoft.
https://github.com/linux-surface/surface-uefi-firmware or the official way through windows.

then i just reinstalled my Distro and and surface-linux again. Test it in the distro live demo usb enviroment before commiting.
now my Surface Book 2 Sleeps when i put it to suspend.

**Comment by DrBrad** [comment]
So you had to uninstall and reinstall your os to pull that off?

**Comment by PiecePaperCode** [comment]
everytime i took the book out the battery was drained. these steps even when drastik were what i dit to make my book sleep

**Comment by DrBrad** [comment]
I will try it, i appreciate the help

**Comment by DrBrad** [comment]
I tried installing the new UEFI with ubuntu, however it doesnt work so I switched to windows and then back to ubuntu and I still have the suspend problem

I have the proper amount of swap allocated.

**Comment by DrBrad** [comment]
> everytime i took the book out the battery was drained. these steps even when drastik were what i dit to make my book sleep

What version on uefi are you on?

**Comment by DrBrad** [comment]
I think it may have to do with iommu and amd_iommu being off or disabled

**Comment by DrBrad** [comment]
Looks like the new v5.15.3 still has the same issue sadly.

**Comment by DrBrad** [comment]
Interesting note, the FN key light will toggle when in the no wake mode, however the cap lock will not.

**Comment by DrBrad** [comment]
Interesting note, the FN key light will toggle when in the no wake mode, however the cap lock will not.

**Comment by martin-lueker** [comment]
I'm wondering if this could be another manifestation of #80 (which seems to occur for my Intel Core device, not just AMD).  Have you tried attaching a USB/keyboard or Mouse to see if that helps it boot?

**Comment by nakato** [comment]
To debug your issue you will need to stop your display manager and work from a terminal, you'll also need to ensure powertop has not done any optimizations, nor thermald, nor TLP were run on the boot you're using for debugging.  They can be added back in slowly to isolate where the issue is occurring.

You will have to debug sleep without the use of systemd commands or accessories plugged in (no monitors or docks).

You'll have to sleep with `echo mem > /sys/power/state` or something like that.  You can check `cat /sys/power/mem_sleep` shows only "[s2idle]".   "deep" should not be displayed, it's not supported by the firmware.

If sleep is fully functional, then something to do with how userspace is managing sleep is causing the issue, systemd has "AllowSuspsendThenHibernate" and "AllowHybridSleep" in /etc/systemd/sleep.conf which mix sleep and hibernation, which mixes sleep and hibernation, which would be the first thing I'd disable to ensure sleep is sleep and hibernation is hibernation.

I don't know how to debug hibernation, my system's partitioning can't use it as my whole disk is a single large btrfs, which means I don't have a swap file/partition to test this with.

Sleep and Hibernate are very different in how they work, so they have to be debugged independently.

I'm running Wayland + KDE with 5.15.11-arch2-1-surface kernel from here.

**Comment by DrBrad** [comment]
Everything works now after the update.

**Comment by A-johani** [comment]
how was the issue resolved cause am facing the same problem ?

**Comment by PiecePaperCode** [comment]
safly it reapeared on my laptop again.
i thing i need to repeat my steps mention above

**Comment by foxharp** [comment]
> Everything works now after the update.

Which update was that?  And, is suspend still working for you, almost a year later?

**Comment by DrBrad** [comment]
I don't recall which update. But ya, no problems at all except still no touch screen.
